version: '3'

volumes:
  postgres_data:

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=tab1k
      - POSTGRES_PASSWORD=TOBI8585
      - POSTGRES_DB=dvc_db
    ports:
      - "5433:5432"

  web:
    build: .
    tty: true
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/code/dvc
      - .:/static
      - .:/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - .:/code/dvc
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web